name: app

type: "php:7.0"

relationships:
    database: "mysql:mysql"

web:
    locations:
        "/":
            root: "Web"
            expires: -1
            passthru: "/index.php"

disk: 512

mounts:
    "/Configuration/Production/": "shared:files/configuration/production"
    "/Configuration/Development/": "shared:files/configuration/development"
    "/Data/Persistent": "shared:files/data"
    "/Data/Temporary": "shared:files/tmp"
    "/Data/Logs": "shared:files/logs"
    "/Web/_Resources": "shared:files/web"

hooks:
    deploy: |
      php flow cache:warmup
    build: |
      php flow doctrine:migrate
      php flow resource:publish
