name: app

type: "php:7.0"

relationships:
    database: "mysql:mysql"

web:
    locations:
        "/":
            root: "Web"
            expires: -1
            passthru: "/index.php"

disk: 512

runtime:
    extensions:
        - imagick
        - gmp
        - redis

mounts:
    "/Configuration/Production": "shared:files/configuration-production"
    "/Configuration/Development": "shared:files/configuration-development"
    "/Data/Persistent": "shared:files/data"
    "/Data/Temporary": "shared:files/tmp"
    "/Data/Logs": "shared:files/logs"
    "/Web/_Resources": "shared:files/web"

hooks:
    deploy: |
      php flow doctrine:migrate
      php flow resource:publish
    build: |
      php flow cache:warmup
