name: app

type: "php:7.0"

relationships:
  database: "mysql:mysql"

web:
  locations:
    "/":
      root: "Web"
      expires: -1
      passthru: "/index.php"

disk: 512

runtime:
  extensions:
    - imagick
    - gmp
    - redis

mounts:
  "/Configuration": "shared:files/configuration"
  "/Data/Persistent": "shared:files/data"
  "/Data/Temporary": "shared:files/tmp"
  "/Data/Logs": "shared:files/logs"
  "/Web/_Resources": "shared:files/web"

hooks:
  build: |
    rm -rf Data/Temporary/*
    php flow cache:warmup
  deploy: |
    cp platform/Flow-Configuration/Settings.yaml Configuration/Settings.yaml
    php platform/platform-set-env.php
